spring:
  cloud:
    stream:
      bindings:

        # This represents your existing in-house system processor
        processOldSystem-in-0:
          destination: dataIn
          binder: kafka
        processOldSystem-out-0:
          destination: dataOut
          binder: rabbit

        # This represents your new (Pulsar custom binder) system processor
        processNewSystem-in-0:
          destination: dataIn
          binder: rabbit
        processNewSystem-out-0:
          destination: dataOut
          binder: rabbit

        #Test sink binding (used for testing)
        sendTestDataOldSystem-out-0:
          destination: dataIn
          binder: kafka
        sendTestDataNewSystem-out-0:
          destination: dataIn
          binder: rabbit
        #Test sink binding (used for testing)
        receive-in-0:
          destination: dataOut
          binder: rabbit

      function:
        definition: sendTestDataOldSystem;sendTestDataNewSystem;processOldSystem;processNewSystem;receive
